use_frameworks!

target 'PowerStone_Example' do
  pod 'PowerStone', :path => '../'

  target 'PowerStone_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
